language: node_js
cache: yarn
notifications:
  email: false
node_js:
  - lts/*
  - node
install: yarn install
branches:
  only:
    - master
    - next
    - beta
    - alpha

jobs:
  include:
    - stage: testing
      #if: branch in (master, develop)
      node_js: lts/*
      env:
        - TEST=test
      script:
        - yarn validate
      after_success:
        - mv packages/react-skeleton/coverage/coverage-final.json
          packages/react-skeleton/coverage/coverage.json

    - stage: release
      # if: branch = master AND commit_message =~ /^[0-9]*\.[0-9]*\.[0-9]*$/
      if: branch = master
      node_js: lts/*
      env:
        - PRODUCTION=production
      script:
        - yarn build
      after_success:
        - echo "Deploying to npm ..."
        - yarn semantic-release

    - stage: deploy
      if: branch = master
      node_js: lts/*
      env:
        - PRODUCTION=production
      script:
        - echo "Deploying to github pages ..."
        - yarn docz
      deploy:
        provider: pages
        local_dir: packages/docs/.docz/dist
        cleanup: false
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
