language: node_js
cache: npm
notifications:
  email: false
node_js:
  - lts/*
  - node
install: npm install
branches:
  only:
    - master
    - next
    - beta
    - alpha

jobs:
  include:
    - stage: testing
      #if: branch in (master, develop)
      node_js: lts/*
      env:
        - TEST=test
      script:
        - npm run validate
      after_success:
        - mv coverage/coverage-final.json coverage/coverage.json
        - codecov

    - stage: release
      # if: branch = master AND commit_message =~ /^[0-9]*\.[0-9]*\.[0-9]*$/
      if: branch = master
      node_js: lts/*
      script:
        - npm run build
      after_success:
        - echo "Deploying to npm ..."
        - npm run semantic-release

    - stage: deploy
      if: branch = master
      node_js: lts/*
      script:
        - echo "Deploying to github pages ..."
        - npm run storybook:build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
